services:
  client:
    build: ./client
    container_name: client
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
    restart: unless-stopped

  server:
    build: ./server
    container_name: server
    network_mode: host
    ports:
      - 3001:3001
    environment:
      PORT: "3001"
      DATABASE_URL: "postgresql://postgres:12345@localhost:5432/POS?schema=public"
      ACCESS_JWT_SECRET: "your access secret"
      REFRESH_JWT_SECRET: "your refresh secret"
      FRONT_END: "http://localhost:3000/"
      NODE_ENV: "dev"
    command: sh -c "npx prisma migrate deploy && npm run seed &&npm run dev"
